import { getMinimumFeeHint, getServiceTypeLabel } from "./defaults";
import {
  applyMenuAddOnOverrides,
  computeMenuAddOnLine,
  getMenuAddOnById,
} from "./menu-add-ons";
import type { EventQuoteInput, QuoteLineItem, QuoteResult } from "./types";

function roundMoney(n: number): number {
  return Math.round(n * 100) / 100;
}

/**
 * Builds customer-facing line items aligned with the `TMSS.26` quoting subtotal (equip + guests + staff + travel + add-ons).
 * Gratuity matches the sheet’s `F31 = F30 * 10%` pattern (percent configurable).
 */
export function buildQuote(input: EventQuoteInput): QuoteResult {
  const equipmentLine: QuoteLineItem = {
    key: "equipment",
    label: "Equipment / service base",
    quantity: 1,
    unitLabel: "event",
    unitAmount: input.equipmentFee,
    lineTotal: roundMoney(input.equipmentFee),
  };

  const guestLine: QuoteLineItem = {
    key: "guest-serving",
    label: "Guest serving (per person)",
    quantity: Math.max(0, input.guestCount),
    unitLabel: "guest",
    unitAmount: input.pricePerGuest,
    lineTotal: roundMoney(
      Math.max(0, input.guestCount) * input.pricePerGuest,
    ),
  };

  const staffLine: QuoteLineItem = {
    key: "staff",
    label: "Staff (hourly × hours × headcount)",
    quantity: Math.max(0, input.staffCount),
    unitLabel: "staff block",
    unitAmount: roundMoney(
      input.laborRatePerHour * Math.max(0, input.serviceHours),
    ),
    lineTotal: roundMoney(
      Math.max(0, input.staffCount) *
        input.laborRatePerHour *
        Math.max(0, input.serviceHours),
    ),
  };

  const travelLine: QuoteLineItem = {
    key: "travel",
    label: "Travel / mileage fee",
    quantity: input.travelFee > 0 ? 1 : 0,
    unitLabel: "flat",
    unitAmount: input.travelFee,
    lineTotal: roundMoney(input.travelFee),
  };

  const addOnLine: QuoteLineItem = {
    key: "addon-flat",
    label: "Other add-ons (flat / manual)",
    quantity: input.addOnFlatTotal > 0 ? 1 : 0,
    unitLabel: "package",
    unitAmount: input.addOnFlatTotal,
    lineTotal: roundMoney(input.addOnFlatTotal),
  };

  const menuAddOnLines: QuoteLineItem[] = [];
  const seenIds = new Set<string>();
  for (const rawId of input.selectedMenuAddOnIds) {
    if (seenIds.has(rawId)) {
      continue;
    }
    seenIds.add(rawId);
    const defBase = getMenuAddOnById(rawId);
    if (!defBase) {
      continue;
    }
    const def = applyMenuAddOnOverrides(
      defBase,
      input.menuAddOnOverrides[rawId],
    );
    const math = computeMenuAddOnLine(def, input.guestCount);
    if (math.lineTotal <= 0) {
      continue;
    }
    menuAddOnLines.push({
      key: `menu-addon:${def.id}`,
      label: `${def.label} (${def.takeRateNote})`,
      quantity: roundMoney(math.effectiveServings),
      unitLabel: "serving",
      unitAmount: def.pricePerServing,
      lineTotal: math.lineTotal,
    });
  }

  const lineItems: QuoteLineItem[] = [
    equipmentLine,
    guestLine,
    staffLine,
    ...menuAddOnLines,
  ];
  if (travelLine.lineTotal > 0) {
    lineItems.push(travelLine);
  }
  if (addOnLine.lineTotal > 0) {
    lineItems.push(addOnLine);
  }

  const subtotal: number = roundMoney(
    lineItems.reduce((sum, li) => sum + li.lineTotal, 0),
  );

  const gPct: number = Math.max(0, input.gratuityPercent) / 100;
  const gratuityAmount: number = roundMoney(subtotal * gPct);
  const grandTotal: number = roundMoney(subtotal + gratuityAmount);

  const minimumHint: number = getMinimumFeeHint(
    input.vehicle,
    input.guestCount,
  );
  let minimumFeeWarning: string | undefined;
  if (grandTotal < minimumHint) {
    const svcLabel: string = getServiceTypeLabel(input.vehicle);
    minimumFeeWarning = `Quoted total is below the usual ${svcLabel} minimum (~${minimumHint}) for this guest band — confirm against the Excel “Minimum Service Fees” block.`;
  }

  return {
    lineItems,
    subtotal,
    gratuityAmount,
    grandTotal,
    internal: {
      minimumFeeWarning,
      suggestedFromZone: `Zone ${input.zone} · ${getServiceTypeLabel(input.vehicle)} · ${input.staffingModel} staff`,
    },
  };
}

export function quoteToEmailText(
  input: EventQuoteInput,
  result: QuoteResult,
): string {
  const scheduleLine: string =
    input.serviceDate.trim() !== ""
      ? `Service window: ${input.serviceStartTime}–${input.serviceEndTime} (${input.serviceTimeZone})`
      : "";
  const lines: string[] = [
    "The Mobile Scoop Shop — quote draft",
    "",
    `Client: ${input.clientName || "TBD"}`,
    `Event date: ${input.eventDate || "TBD"}`,
    scheduleLine,
    input.venueNotes ? `Notes: ${input.venueNotes}` : "",
    "",
    "Line items:",
    ...result.lineItems.map(
      (li) =>
        `• ${li.label}: ${li.quantity} × ${formatUsd(li.unitAmount)} = ${formatUsd(li.lineTotal)}`,
    ),
    "",
    `Subtotal: ${formatUsd(result.subtotal)}`,
    `Gratuity: ${formatUsd(result.gratuityAmount)}`,
    `Total: ${formatUsd(result.grandTotal)}`,
    "",
    "—",
    "Generated by MSS Quote App (verify against your master workbook before sending).",
  ].filter(Boolean);
  return lines.join("\n");
}

function formatUsd(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(n);
}
